# infra/test/docker-compose.yaml
version: '3.8'

services:
  mysql:
    image: mysql:8.2.0
    environment:
      MYSQL_DATABASE: integration_tests_db
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
      MYSQL_ROOT_PASSWORD: sa
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password


volumes:
  mysql-data:
